In [1]:
#의사결정나무
#랜덤포레스트
#KNN
#로지스틱 회귀(절편이랑 기울기로 구하기)

In [2]:
from google.colab import files
uploaded = files.upload()

Saving winequality-white.csv to winequality-white.csv


In [3]:
import pandas as pd

# 파일 경로를 지정합니다.
file_path = 'winequality-white.csv'

# pd.read_csv를 사용하되, delimiter=';' 옵션을 추가하여
# 세미콜론을 기준으로 데이터를 나누도록 설정합니다.
df = pd.read_csv(file_path, delimiter=';')

# 데이터가 잘 나뉘었는지 확인하기 위해 상위 5개 행을 출력합니다.
print(df.head())

   fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6 

In [36]:
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.tree import DecisionTreeClassifier

from sklearn.ensemble import RandomForestClassifier

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

from sklearn.neighbors import KNeighborsClassifier

In [5]:
df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [7]:
df['quality'].value_counts()

quality
6    2198
5    1457
7     880
8     175
4     163
3      20
9       5
Name: count, dtype: int64

In [24]:
cols = ['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality']

#여기서도 deliniter=';'를 지정하여 csv파일 내의 데이터를 ;를 기준으로 나눈다
df = pd.read_csv("winequality-white.csv",header=None, names=cols, delimiter=';').dropna()

In [25]:
#타겟 데이터에 결측값이 있나 확인하기
df["quality"].value_counts()

quality
6          2198
5          1457
7           880
8           175
4           163
3            20
9             5
quality       1
Name: count, dtype: int64

In [26]:
#결측치 확인하기
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [27]:
#결측치를 제거하는 과정
df = df.dropna()
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [28]:
# 모든 레이블을 숫자로 변형 -> 머신러닝은 문자로 된 데이터는 읽지 못한다.

from sklearn.preprocessing import LabelEncoder

label_encoders = {}
for column in df.columns:
    label_encoders[column] = LabelEncoder()
    df[column] = label_encoders[column].fit_transform(df[column])

In [29]:
#타겟 데이터로 사용할 quality 제외
input = df.drop(columns=["quality"])

#quality을 타겟 데이터로 선택
target = df["quality"]

In [30]:
target

0       7
1       3
2       3
3       3
4       3
       ..
4894    3
4895    2
4896    3
4897    4
4898    3
Name: quality, Length: 4899, dtype: int64

In [31]:
#훈련세트와 테스트 세트 분리
train_input, test_input, train_target, test_target = train_test_split(input, target, test_size=0.2, random_state=42)

In [32]:
train_input.shape, test_input.shape, train_target.shape, test_target.shape

((3919, 11), (980, 11), (3919,), (980,))

In [44]:
#회귀 모델 생성(스케일링 적용하기)
#스케일링을 하기 전에 훈련세트와 테스트 세트를 먼저 분리해 주어야함
#특정 모델을 위해서 하는게 아니라 머신러닝과 딥러닝 모델에서는 기본적으로 스케일링을 진행함
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()

ss.fit(train_input)

train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)

In [45]:
#의사결정 나무 모델 생성
dt = DecisionTreeClassifier(random_state=42)
#랜덤 포레스트 모델 생성
rf = RandomForestClassifier(n_estimators=200, random_state=42)
#로지스틱 회귀 모델 생성
lr = LogisticRegression(max_iter=500)
#KNN 분류 모델 생성
kn = KNeighborsClassifier()

In [46]:
#모델 학습 시키기
dt.fit(train_input, train_target)
rf.fit(train_input, train_target)
lr.fit(train_input, train_target)
kn.fit(train_input, train_target)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


KNeighborsClassifier()

In [43]:
#로지스틱 회귀 모델의 기울기와 절편 확인하기
print(lr.coef_, lr.intercept_)

[[-5.66207810e-02  1.62213492e-02  1.37460648e-02 -3.01754961e-03
   5.07579159e-03 -1.10628986e-02  6.04821152e-03  4.35125936e-03
  -2.97184598e-02 -3.24649027e-02 -8.22926277e-03]
 [-9.09098894e-04  2.69141706e-02 -1.96362614e-02 -2.21432901e-03
   1.47863113e-02  5.05037887e-03  2.71470363e-03  2.12291345e-03
  -1.83887946e-02 -1.52865745e-02 -3.79268462e-03]
 [ 8.17759177e-03  5.73634080e-03 -3.42855423e-04  3.17654992e-04
   1.53966574e-02  5.62946485e-03  9.94450502e-04  2.89339933e-03
   1.59261905e-03 -1.85497969e-03  7.00272632e-03]
 [ 2.46466466e-02 -1.32100773e-02  7.63686929e-03  2.02991857e-03
   9.65217072e-03  9.39518568e-03  1.72086458e-03  8.29956156e-04
   1.47291871e-02  1.75605086e-02  4.40938610e-03]
 [ 4.23228269e-02 -1.87570964e-02  6.97489328e-04  3.09765541e-03
  -1.79381709e-02  9.70381605e-03 -2.37763527e-05 -2.03620271e-03
   2.61045556e-02  2.64627194e-02  8.21072557e-03]
 [ 1.86242382e-02 -1.33743163e-02  3.47286213e-03  3.76287586e-03
  -2.33843078e-02  

In [47]:
print(lr.coef_.shape, lr.intercept_.shape)

(8, 11) (8,)


In [39]:
#모델 예측 결과 생성

dt_pred = dt.predict(test_input)
rf_pred = rf.predict(test_input)
lr_pred = lr.predict(test_input)
kn_pred = kn.predict(test_input)

In [41]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

dt_acc = accuracy_score(test_target, dt_pred)
rf_acc = accuracy_score(test_target, rf_pred )
lr_acc = accuracy_score(test_target, lr_pred)
kn_acc = accuracy_score(test_target, kn_pred)


print("=== DT Test Accuracy ===")
print(f"Decision Tree : {dt_acc:.4f}")
print (confusion_matrix(test_target,dt_pred))

print("=== RF Test Accuracy ===")
print(f"Random Forest : {rf_acc:.4f}")
print (confusion_matrix(test_target,rf_pred))

print("=== LR Test Accuracy ===")
print(f"Logistic Reg. : {lr_acc:.4f}")
print (confusion_matrix(test_target,lr_pred))

print("=== KN Test Accuracy ===")
print(f"Logistic Reg. : {lr_acc:.4f}")
print (confusion_matrix(test_target,kn_pred))

=== DT Test Accuracy ===
Decision Tree : 0.6286
[[  0   0   2   2   0   0   0]
 [  0   9  11  15   3   0   0]
 [  1   8 180  63   9   1   1]
 [  1  10  86 300  57   5   0]
 [  1   2   8  55 107   5   0]
 [  0   0   2   9   5  20   0]
 [  0   0   0   1   1   0   0]]
=== RF Test Accuracy ===
Random Forest : 0.6918
[[  0   0   2   1   1   0   0]
 [  0  11  13  14   0   0   0]
 [  0   0 191  71   1   0   0]
 [  0   1  63 364  29   2   0]
 [  0   0   1  78  97   2   0]
 [  0   0   0  13   8  15   0]
 [  0   0   0   1   1   0   0]]
=== LR Test Accuracy ===
Logistic Reg. : 0.4990
[[  0   0   1   2   1   0   0]
 [  0   2  16  19   1   0   0]
 [  0   2 121 138   2   0   0]
 [  0   0 103 331  25   0   0]
 [  0   0  19 124  35   0   0]
 [  0   0   4  18  14   0   0]
 [  0   0   0   0   2   0   0]]
=== KN Test Accuracy ===
Logistic Reg. : 0.4990
[[  0   0   3   0   1   0   0]
 [  0   4  17  15   2   0   0]
 [  0   5 156  96   5   1   0]
 [  0   5 126 264  64   0   0]
 [  0   2  10  85  81   0   0]